GET http://localhost:5100/games

### 
GET http://localhost:5100/games/4

###
POST http://localhost:5100/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Kid and Family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5100/games/1
Content-Type: application/json

{
    "id": 1,
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 19.99,
    "releaseDate": "1997-11-15"
}


###
DELETE http://localhost:5100/games/2