GET http://localhost:5100/games

### 
GET http://localhost:5100/games/1

###
POST http://localhost:5100/games
Content-Type: application/json

{
  "name": "GTA III",
  "genreId": 1,
  "price": 9.99,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5100/games/1
Content-Type: application/json

{
    "name": "GTA III Remastered",
    "genreId": 1,
    "price": 29.99,
    "releaseDate": "2019-12-25"
}


###
DELETE http://localhost:5100/games/2